path = ["C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.10.2383.0_x64__8wekyb3d8bbwe", "C:\\VulkanSDK\\1.2.189.0\\Bin", "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath", "C:\\Python39\\Scripts\\", "C:\\Python39\\", "C:\\VulkanSDK\\1.2.176.1\\Bin", "C:\\Program Files\\Kalker\\", "C:\\Program Files\\AdoptOpenJDK\\jdk-16.0.1.9-hotspot\\bin", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\", "C:\\Windows\\System32\\OpenSSH\\", "C:\\ProgramData\\chocolatey\\bin", "C:\\ProgramData\\chocolatey\\lib\\gsudo\\bin\\", "C:\\Program Files\\dotnet\\", "C:\\Program Files\\Microsoft VS Code\\bin", "C:\\Program Files (x86)\\dotnet\\", "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common", "C:\\Program Files\\RepoZ", "C:\\ProgramData\\nxxm", "C:\\Program Files\\PowerShell\\7\\", "C:\\Program Files\\Meson\\", "C:\\Program Files\\LLVM\\bin", "C:\\Program Files\\nodejs\\", "C:\\ProgramData\\nvm", "C:\\Program Files\\nodejs", "C:\\Program Files\\Git\\cmd", "C:\\Program Files\\Airshipper\\", "C:\\Program Files\\Sturdy\\", "C:\\Program Files\\Conan\\conan", "C:\\Users\\Bay\\scoop\\shims", "C:\\Users\\Bay\\.cargo\\bin", "C:\\Users\\Bay\\AppData\\Local\\Microsoft\\WindowsApps", "C:\\Users\\Bay\\.dotnet\\tools", "C:\\Users\\Bay\\AppData\\Local\\Programs\\oh-my-posh\\bin", "C:\\Users\\Bay\\AppData\\Local\\Programs\\oh-my-posh\\themes", "C:\\tools\\neovim\\Neovim\\bin", "C:\\build2\\bin", "C:\\Users\\Bay\\AppData\\Local\\Programs\\Microsoft VS Code\\bin", "C:\\Users\\Bay\\.dotnet\\tools", "C:\\tools\\premake", "C:\\Users\\Bay\\go\\bin", "C:\\Program Files\\Onivim2", "C:\\tools\\NonStickMouse", "C:\\Users\\Bay\\AppData\\Roaming\\npm", "C:\\Program Files\\CMake\\bin", "", "C:\\Users\\Bay\\xmake", "C:\\Exercism", "C:\\Users\\Bay\\.dotnet\\tools"]
pivot_mode = "always"
skip_welcome_message = true
startup = [
"mkdir ~/.cache/starship",
"starship init nu | save ~/.cache/starship/init.nu",
"source ~/.cache/starship/init.nu",
"zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu"
]
prompt = "starship_prompt"

[env]
"=::" = "::\\"
ALLUSERSPROFILE = "C:\\ProgramData"
APPDATA = "C:\\Users\\Bay\\AppData\\Roaming"
CMD_DURATION_MS = "0"
COMPUTERNAME = "DESKTOP-ARQGOH4"
ChocolateyInstall = "C:\\ProgramData\\chocolatey"
ChocolateyLastPathUpdate = "132710475167478124"
ChocolateyToolsLocation = "C:\\tools"
ComSpec = "C:\\Windows\\system32\\cmd.exe"
CommonProgramFiles = "C:\\Program Files\\Common Files"
"CommonProgramFiles(x86)" = "C:\\Program Files (x86)\\Common Files"
CommonProgramW6432 = "C:\\Program Files\\Common Files"
DriverData = "C:\\Windows\\System32\\Drivers\\DriverData"
HOMEDRIVE = "C:"
HOMEPATH = "\\Users\\Bay"
JAVA_HOME = "C:\\Program Files\\AdoptOpenJDK\\jdk-16.0.1.9-hotspot\\"
LOCALAPPDATA = "C:\\Users\\Bay\\AppData\\Local"
LOGONSERVER = "\\\\DESKTOP-ARQGOH4"
NUMBER_OF_PROCESSORS = "16"
NVM_HOME = "C:\\ProgramData\\nvm"
NVM_SYMLINK = "C:\\Program Files\\nodejs"
OS = "Windows_NT"
OneDrive = "D:\\OneDrive"
OneDriveConsumer = "D:\\OneDrive"
PATHEXT = ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
POWERSHELL_DISTRIBUTION_CHANNEL = "MSI:Windows 10 Pro"
PROCESSOR_ARCHITECTURE = "AMD64"
PROCESSOR_IDENTIFIER = "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD"
PROCESSOR_LEVEL = "23"
PROCESSOR_REVISION = "0802"
PSModulePath = "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules"
PUBLIC = "C:\\Users\\Public"
ProgramData = "C:\\ProgramData"
ProgramFiles = "C:\\Program Files"
"ProgramFiles(x86)" = "C:\\Program Files (x86)"
ProgramW6432 = "C:\\Program Files"
SESSIONNAME = "Console"
SystemDrive = "C:"
SystemRoot = "C:\\Windows"
TEMP = "C:\\Users\\Bay\\AppData\\Local\\Temp"
TMP = "C:\\Users\\Bay\\AppData\\Local\\Temp"
USERDOMAIN = "DESKTOP-ARQGOH4"
USERDOMAIN_ROAMINGPROFILE = "DESKTOP-ARQGOH4"
USERNAME = "Bay"
USERPROFILE = "C:\\Users\\Bay"
VK_SDK_PATH = "C:\\VulkanSDK\\1.2.189.0"
VULKAN_SDK = "C:\\VulkanSDK\\1.2.189.0"
WSLENV = "WT_SESSION::WT_PROFILE_ID"
WT_PROFILE_ID = "{afeefd58-501c-4a5e-b7b4-d21b7c1624bf}"
WT_SESSION = "5b14af18-16d6-4af6-bedf-23b5ec5cd0b6"
windir = "C:\\Windows"
