skip_welcome_message = true

startup = [
"alias cls = clear",
"alias nv = neovide",
"alias appdata = $nu.env.APPDATA",
"alias s = scoop install",
"alias sr = scoop uninstall",
"mkdir ~/.cache/starship",
"starship init nu | save ~/.cache/starship/init.nu",
"source ~/.cache/starship/init.nu",
"zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu"
]

prompt = "starship_prompt"
